//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        public BAN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string SOBAN { get; set; }
        public string TENBAN { get; set; }
        public string TINHTRANGBAN { get; set; }
        public string MAKHUVUC { get; set; }
        public string matrangthai { get; set; }
        public Nullable<System.DateTime> NGAYXOABAN { get; set; }
    
        public virtual KHUVUC KHUVUC { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
