//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCVU
    {
        public CHUCVU()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
            this.QUYENHANs = new HashSet<QUYENHAN>();
        }
    
        public string MACV { get; set; }
        public string TENCV { get; set; }
    
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
        public virtual ICollection<QUYENHAN> QUYENHANs { get; set; }
    }
}
