//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEUKIENKM
    {
        public DIEUKIENKM()
        {
            this.QUANHE_HD_DKKM = new HashSet<QUANHE_HD_DKKM>();
        }
    
        public string MADIEUKIENKM { get; set; }
        public string MAKM { get; set; }
        public string MATHUCUONG { get; set; }
        public string MAMONAN { get; set; }
        public Nullable<long> DIEMTANG { get; set; }
        public Nullable<decimal> PHANTRAMGIAMGIA { get; set; }
        public Nullable<long> TONGTIENMUA { get; set; }
    
        public virtual CHUONGTRINHKM CHUONGTRINHKM { get; set; }
        public virtual ICollection<QUANHE_HD_DKKM> QUANHE_HD_DKKM { get; set; }
    }
}
