//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string DIENTHOAIKH { get; set; }
        public string DIACHIKH { get; set; }
        public System.DateTime NGAYSINHKH { get; set; }
        public string EMAILKH { get; set; }
        public Nullable<decimal> DIEM { get; set; }
        public Nullable<long> TIENDATIEU { get; set; }
        public string MALOAIKH { get; set; }
        public Nullable<System.DateTime> ngaydangky { get; set; }
        public string matrangthai { get; set; }
        public Nullable<System.DateTime> NGAYXOATK { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual LOAIKH LOAIKH { get; set; }
    }
}
