//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUVUC
    {
        public KHUVUC()
        {
            this.BANs = new HashSet<BAN>();
        }
    
        public string MAKHUVUC { get; set; }
        public string TENKHUVUC { get; set; }
    
        public virtual ICollection<BAN> BANs { get; set; }
    }
}
