//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        public MONAN()
        {
            this.CTHD_MA = new HashSet<CTHD_MA>();
        }
    
        public string MAMON { get; set; }
        public string TENMON { get; set; }
        public int GIABAN { get; set; }
        public string MOTA { get; set; }
        public string DVT { get; set; }
        public byte[] HINH { get; set; }
        public string matrangthai { get; set; }
        public Nullable<System.DateTime> NGAYXOAMON { get; set; }
    
        public virtual ICollection<CTHD_MA> CTHD_MA { get; set; }
    }
}
