//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MANV { get; set; }
        public string MACV { get; set; }
        public string MABP { get; set; }
        public string TENNV { get; set; }
        public string DIENTHOAINV { get; set; }
        public string EMAILNV { get; set; }
        public string DIACHINV { get; set; }
        public string SOTAIKHOANNV { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<System.DateTime> NGAYVAOLAM { get; set; }
        public string matrangthai { get; set; }
        public Nullable<System.DateTime> NGAYROIKHOI { get; set; }
    
        public virtual BOPHAN BOPHAN { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
