//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAN> BANs { get; set; }
        public DbSet<BOPHAN> BOPHANs { get; set; }
        public DbSet<CHUCVU> CHUCVUs { get; set; }
        public DbSet<CHUONGTRINHKM> CHUONGTRINHKMs { get; set; }
        public DbSet<DIEUKIENKM> DIEUKIENKMs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<KHO> KHOes { get; set; }
        public DbSet<KHUVUC> KHUVUCs { get; set; }
        public DbSet<LOAICTKM> LOAICTKMs { get; set; }
        public DbSet<LOAIKH> LOAIKHs { get; set; }
        public DbSet<MONAN> MONANs { get; set; }
        public DbSet<NGUYENLIEU> NGUYENLIEUx { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<QUANHE_HD_DKKM> QUANHE_HD_DKKM { get; set; }
        public DbSet<QUYENHAN> QUYENHANs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<THUCUONG> THUCUONGs { get; set; }
        public DbSet<TONKHO> TONKHOes { get; set; }
        public DbSet<TRANGTHAI> TRANGTHAIs { get; set; }
        public DbSet<CTHD_MA> CTHD_MA { get; set; }
        public DbSet<CTHD_TU> CTHD_TU { get; set; }
    
        public virtual int CapNhatNgayHetHanKm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatNgayHetHanKm");
        }
    
        public virtual ObjectResult<checkKmMA_Result> checkKmMA(string mamonan)
        {
            var mamonanParameter = mamonan != null ?
                new ObjectParameter("mamonan", mamonan) :
                new ObjectParameter("mamonan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<checkKmMA_Result>("checkKmMA", mamonanParameter);
        }
    
        public virtual ObjectResult<checkKmTU_Result> checkKmTU(string mathucuong)
        {
            var mathucuongParameter = mathucuong != null ?
                new ObjectParameter("mathucuong", mathucuong) :
                new ObjectParameter("mathucuong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<checkKmTU_Result>("checkKmTU", mathucuongParameter);
        }
    
        public virtual ObjectResult<dangkydangnhap_Result> dangkydangnhap(string mANV, string tENDANGNHAP, string mATKHAU, string request)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var tENDANGNHAPParameter = tENDANGNHAP != null ?
                new ObjectParameter("TENDANGNHAP", tENDANGNHAP) :
                new ObjectParameter("TENDANGNHAP", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dangkydangnhap_Result>("dangkydangnhap", mANVParameter, tENDANGNHAPParameter, mATKHAUParameter, requestParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> LayTongDoanhThuTruocThue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("LayTongDoanhThuTruocThue");
        }
    
        public virtual ObjectResult<Nullable<double>> LayTongVatHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("LayTongVatHoaDon");
        }
    
        public virtual ObjectResult<loadbxhmonan_Result> loadbxhmonan(string mocthoigian, string tungay, string denngay)
        {
            var mocthoigianParameter = mocthoigian != null ?
                new ObjectParameter("mocthoigian", mocthoigian) :
                new ObjectParameter("mocthoigian", typeof(string));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loadbxhmonan_Result>("loadbxhmonan", mocthoigianParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<loadbxhnhanvien_Result> loadbxhnhanvien(string mocthoigian)
        {
            var mocthoigianParameter = mocthoigian != null ?
                new ObjectParameter("mocthoigian", mocthoigian) :
                new ObjectParameter("mocthoigian", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loadbxhnhanvien_Result>("loadbxhnhanvien", mocthoigianParameter);
        }
    
        public virtual ObjectResult<loadbxhthucuong_Result> loadbxhthucuong(string mocthoigian, string tungay, string denngay)
        {
            var mocthoigianParameter = mocthoigian != null ?
                new ObjectParameter("mocthoigian", mocthoigian) :
                new ObjectParameter("mocthoigian", typeof(string));
    
            var tungayParameter = tungay != null ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(string));
    
            var denngayParameter = denngay != null ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loadbxhthucuong_Result>("loadbxhthucuong", mocthoigianParameter, tungayParameter, denngayParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SuaBan(string sOBAN, string tENBAN, string mAKHUVUC)
        {
            var sOBANParameter = sOBAN != null ?
                new ObjectParameter("SOBAN", sOBAN) :
                new ObjectParameter("SOBAN", typeof(string));
    
            var tENBANParameter = tENBAN != null ?
                new ObjectParameter("TENBAN", tENBAN) :
                new ObjectParameter("TENBAN", typeof(string));
    
            var mAKHUVUCParameter = mAKHUVUC != null ?
                new ObjectParameter("MAKHUVUC", mAKHUVUC) :
                new ObjectParameter("MAKHUVUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaBan", sOBANParameter, tENBANParameter, mAKHUVUCParameter);
        }
    
        public virtual int thaotacchitiethoadon(string mAHD, string mAMON, Nullable<int> sOLUONG, string request)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            var mAMONParameter = mAMON != null ?
                new ObjectParameter("MAMON", mAMON) :
                new ObjectParameter("MAMON", typeof(string));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("thaotacchitiethoadon", mAHDParameter, mAMONParameter, sOLUONGParameter, requestParameter);
        }
    
        public virtual int thaotachoadon(string mAHD, string mAKH, string mANV, Nullable<System.DateTime> nGAYLAP, string nOIDUNG, string hTTT, string sOBAN, string tINHTRANGHD, Nullable<double> vAT, Nullable<long> tIENSAUTHUE, Nullable<long> tIENNHANKH, Nullable<long> tIENTRALAIKH, string makm, string request)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var nGAYLAPParameter = nGAYLAP.HasValue ?
                new ObjectParameter("NGAYLAP", nGAYLAP) :
                new ObjectParameter("NGAYLAP", typeof(System.DateTime));
    
            var nOIDUNGParameter = nOIDUNG != null ?
                new ObjectParameter("NOIDUNG", nOIDUNG) :
                new ObjectParameter("NOIDUNG", typeof(string));
    
            var hTTTParameter = hTTT != null ?
                new ObjectParameter("HTTT", hTTT) :
                new ObjectParameter("HTTT", typeof(string));
    
            var sOBANParameter = sOBAN != null ?
                new ObjectParameter("SOBAN", sOBAN) :
                new ObjectParameter("SOBAN", typeof(string));
    
            var tINHTRANGHDParameter = tINHTRANGHD != null ?
                new ObjectParameter("TINHTRANGHD", tINHTRANGHD) :
                new ObjectParameter("TINHTRANGHD", typeof(string));
    
            var vATParameter = vAT.HasValue ?
                new ObjectParameter("VAT", vAT) :
                new ObjectParameter("VAT", typeof(double));
    
            var tIENSAUTHUEParameter = tIENSAUTHUE.HasValue ?
                new ObjectParameter("TIENSAUTHUE", tIENSAUTHUE) :
                new ObjectParameter("TIENSAUTHUE", typeof(long));
    
            var tIENNHANKHParameter = tIENNHANKH.HasValue ?
                new ObjectParameter("TIENNHANKH", tIENNHANKH) :
                new ObjectParameter("TIENNHANKH", typeof(long));
    
            var tIENTRALAIKHParameter = tIENTRALAIKH.HasValue ?
                new ObjectParameter("TIENTRALAIKH", tIENTRALAIKH) :
                new ObjectParameter("TIENTRALAIKH", typeof(long));
    
            var makmParameter = makm != null ?
                new ObjectParameter("makm", makm) :
                new ObjectParameter("makm", typeof(string));
    
            var requestParameter = request != null ?
                new ObjectParameter("request", request) :
                new ObjectParameter("request", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("thaotachoadon", mAHDParameter, mAKHParameter, mANVParameter, nGAYLAPParameter, nOIDUNGParameter, hTTTParameter, sOBANParameter, tINHTRANGHDParameter, vATParameter, tIENSAUTHUEParameter, tIENNHANKHParameter, tIENTRALAIKHParameter, makmParameter, requestParameter);
        }
    
        public virtual int thaotackhachhang(string makh, string tenkh, string dienthoaikh, string diachikh, Nullable<System.DateTime> ngaysinhkh, string emailkh, Nullable<decimal> diem, Nullable<long> tiendatieu, string maloaikh, Nullable<System.DateTime> ngaydangky, string matrangthai, string request)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            var dienthoaikhParameter = dienthoaikh != null ?
                new ObjectParameter("dienthoaikh", dienthoaikh) :
                new ObjectParameter("dienthoaikh", typeof(string));
    
            var diachikhParameter = diachikh != null ?
                new ObjectParameter("diachikh", diachikh) :
                new ObjectParameter("diachikh", typeof(string));
    
            var ngaysinhkhParameter = ngaysinhkh.HasValue ?
                new ObjectParameter("ngaysinhkh", ngaysinhkh) :
                new ObjectParameter("ngaysinhkh", typeof(System.DateTime));
    
            var emailkhParameter = emailkh != null ?
                new ObjectParameter("emailkh", emailkh) :
                new ObjectParameter("emailkh", typeof(string));
    
            var diemParameter = diem.HasValue ?
                new ObjectParameter("diem", diem) :
                new ObjectParameter("diem", typeof(decimal));
    
            var tiendatieuParameter = tiendatieu.HasValue ?
                new ObjectParameter("tiendatieu", tiendatieu) :
                new ObjectParameter("tiendatieu", typeof(long));
    
            var maloaikhParameter = maloaikh != null ?
                new ObjectParameter("maloaikh", maloaikh) :
                new ObjectParameter("maloaikh", typeof(string));
    
            var ngaydangkyParameter = ngaydangky.HasValue ?
                new ObjectParameter("ngaydangky", ngaydangky) :
                new ObjectParameter("ngaydangky", typeof(System.DateTime));
    
            var matrangthaiParameter = matrangthai != null ?
                new ObjectParameter("matrangthai", matrangthai) :
                new ObjectParameter("matrangthai", typeof(string));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("thaotackhachhang", makhParameter, tenkhParameter, dienthoaikhParameter, diachikhParameter, ngaysinhkhParameter, emailkhParameter, diemParameter, tiendatieuParameter, maloaikhParameter, ngaydangkyParameter, matrangthaiParameter, requestParameter);
        }
    
        public virtual int themban(string sOBAN, string tENBAN, string tINHTRANGBAN, string mAKHUVUC, string matrangthai)
        {
            var sOBANParameter = sOBAN != null ?
                new ObjectParameter("SOBAN", sOBAN) :
                new ObjectParameter("SOBAN", typeof(string));
    
            var tENBANParameter = tENBAN != null ?
                new ObjectParameter("TENBAN", tENBAN) :
                new ObjectParameter("TENBAN", typeof(string));
    
            var tINHTRANGBANParameter = tINHTRANGBAN != null ?
                new ObjectParameter("TINHTRANGBAN", tINHTRANGBAN) :
                new ObjectParameter("TINHTRANGBAN", typeof(string));
    
            var mAKHUVUCParameter = mAKHUVUC != null ?
                new ObjectParameter("MAKHUVUC", mAKHUVUC) :
                new ObjectParameter("MAKHUVUC", typeof(string));
    
            var matrangthaiParameter = matrangthai != null ?
                new ObjectParameter("matrangthai", matrangthai) :
                new ObjectParameter("matrangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themban", sOBANParameter, tENBANParameter, tINHTRANGBANParameter, mAKHUVUCParameter, matrangthaiParameter);
        }
    
        public virtual int themchuongtrinhkm(string makm, string maloaikm, string tenkm, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc, string trangthai, string ghichu)
        {
            var makmParameter = makm != null ?
                new ObjectParameter("makm", makm) :
                new ObjectParameter("makm", typeof(string));
    
            var maloaikmParameter = maloaikm != null ?
                new ObjectParameter("maloaikm", maloaikm) :
                new ObjectParameter("maloaikm", typeof(string));
    
            var tenkmParameter = tenkm != null ?
                new ObjectParameter("tenkm", tenkm) :
                new ObjectParameter("tenkm", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themchuongtrinhkm", makmParameter, maloaikmParameter, tenkmParameter, ngaybatdauParameter, ngayketthucParameter, trangthaiParameter, ghichuParameter);
        }
    
        public virtual int themdieukienkm(string madieukienkm, string makm, string mathucuong, string mamonan, Nullable<long> diemtang, Nullable<decimal> phantramgiamgia, Nullable<long> tongtienmua)
        {
            var madieukienkmParameter = madieukienkm != null ?
                new ObjectParameter("madieukienkm", madieukienkm) :
                new ObjectParameter("madieukienkm", typeof(string));
    
            var makmParameter = makm != null ?
                new ObjectParameter("makm", makm) :
                new ObjectParameter("makm", typeof(string));
    
            var mathucuongParameter = mathucuong != null ?
                new ObjectParameter("mathucuong", mathucuong) :
                new ObjectParameter("mathucuong", typeof(string));
    
            var mamonanParameter = mamonan != null ?
                new ObjectParameter("mamonan", mamonan) :
                new ObjectParameter("mamonan", typeof(string));
    
            var diemtangParameter = diemtang.HasValue ?
                new ObjectParameter("diemtang", diemtang) :
                new ObjectParameter("diemtang", typeof(long));
    
            var phantramgiamgiaParameter = phantramgiamgia.HasValue ?
                new ObjectParameter("phantramgiamgia", phantramgiamgia) :
                new ObjectParameter("phantramgiamgia", typeof(decimal));
    
            var tongtienmuaParameter = tongtienmua.HasValue ?
                new ObjectParameter("tongtienmua", tongtienmua) :
                new ObjectParameter("tongtienmua", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themdieukienkm", madieukienkmParameter, makmParameter, mathucuongParameter, mamonanParameter, diemtangParameter, phantramgiamgiaParameter, tongtienmuaParameter);
        }
    
        public virtual int themmonan(string mAMON, string tENMON, Nullable<int> gIABAN, string mOTA, string dVT, byte[] hINH, string request, string matrangthai)
        {
            var mAMONParameter = mAMON != null ?
                new ObjectParameter("MAMON", mAMON) :
                new ObjectParameter("MAMON", typeof(string));
    
            var tENMONParameter = tENMON != null ?
                new ObjectParameter("TENMON", tENMON) :
                new ObjectParameter("TENMON", typeof(string));
    
            var gIABANParameter = gIABAN.HasValue ?
                new ObjectParameter("GIABAN", gIABAN) :
                new ObjectParameter("GIABAN", typeof(int));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var hINHParameter = hINH != null ?
                new ObjectParameter("HINH", hINH) :
                new ObjectParameter("HINH", typeof(byte[]));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            var matrangthaiParameter = matrangthai != null ?
                new ObjectParameter("matrangthai", matrangthai) :
                new ObjectParameter("matrangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themmonan", mAMONParameter, tENMONParameter, gIABANParameter, mOTAParameter, dVTParameter, hINHParameter, requestParameter, matrangthaiParameter);
        }
    
        public virtual int themnhanvien(string mANV, string mACV, string mABP, string tENNV, string dIENTHOAINV, string eMAILNV, string dIACHINV, string sOTAIKHOANNV, string tENDANGNHAP, string mATKHAU, Nullable<System.DateTime> nGAYVAOLAM, string request, string matrangthai)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var mACVParameter = mACV != null ?
                new ObjectParameter("MACV", mACV) :
                new ObjectParameter("MACV", typeof(string));
    
            var mABPParameter = mABP != null ?
                new ObjectParameter("MABP", mABP) :
                new ObjectParameter("MABP", typeof(string));
    
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var dIENTHOAINVParameter = dIENTHOAINV != null ?
                new ObjectParameter("DIENTHOAINV", dIENTHOAINV) :
                new ObjectParameter("DIENTHOAINV", typeof(string));
    
            var eMAILNVParameter = eMAILNV != null ?
                new ObjectParameter("EMAILNV", eMAILNV) :
                new ObjectParameter("EMAILNV", typeof(string));
    
            var dIACHINVParameter = dIACHINV != null ?
                new ObjectParameter("DIACHINV", dIACHINV) :
                new ObjectParameter("DIACHINV", typeof(string));
    
            var sOTAIKHOANNVParameter = sOTAIKHOANNV != null ?
                new ObjectParameter("SOTAIKHOANNV", sOTAIKHOANNV) :
                new ObjectParameter("SOTAIKHOANNV", typeof(string));
    
            var tENDANGNHAPParameter = tENDANGNHAP != null ?
                new ObjectParameter("TENDANGNHAP", tENDANGNHAP) :
                new ObjectParameter("TENDANGNHAP", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var nGAYVAOLAMParameter = nGAYVAOLAM.HasValue ?
                new ObjectParameter("NGAYVAOLAM", nGAYVAOLAM) :
                new ObjectParameter("NGAYVAOLAM", typeof(System.DateTime));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            var matrangthaiParameter = matrangthai != null ?
                new ObjectParameter("matrangthai", matrangthai) :
                new ObjectParameter("matrangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themnhanvien", mANVParameter, mACVParameter, mABPParameter, tENNVParameter, dIENTHOAINVParameter, eMAILNVParameter, dIACHINVParameter, sOTAIKHOANNVParameter, tENDANGNHAPParameter, mATKHAUParameter, nGAYVAOLAMParameter, requestParameter, matrangthaiParameter);
        }
    
        public virtual int themthucuong(string mATHUCUONG, string tENTHUCUONG, string mOTA, string dVT, Nullable<int> gIABAN, byte[] hINH, string request, string matrangthai)
        {
            var mATHUCUONGParameter = mATHUCUONG != null ?
                new ObjectParameter("MATHUCUONG", mATHUCUONG) :
                new ObjectParameter("MATHUCUONG", typeof(string));
    
            var tENTHUCUONGParameter = tENTHUCUONG != null ?
                new ObjectParameter("TENTHUCUONG", tENTHUCUONG) :
                new ObjectParameter("TENTHUCUONG", typeof(string));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var gIABANParameter = gIABAN.HasValue ?
                new ObjectParameter("GIABAN", gIABAN) :
                new ObjectParameter("GIABAN", typeof(int));
    
            var hINHParameter = hINH != null ?
                new ObjectParameter("HINH", hINH) :
                new ObjectParameter("HINH", typeof(byte[]));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            var matrangthaiParameter = matrangthai != null ?
                new ObjectParameter("matrangthai", matrangthai) :
                new ObjectParameter("matrangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themthucuong", mATHUCUONGParameter, tENTHUCUONGParameter, mOTAParameter, dVTParameter, gIABANParameter, hINHParameter, requestParameter, matrangthaiParameter);
        }
    
        public virtual int updateDiem(Nullable<decimal> sodiem, string makh)
        {
            var sodiemParameter = sodiem.HasValue ?
                new ObjectParameter("sodiem", sodiem) :
                new ObjectParameter("sodiem", typeof(decimal));
    
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateDiem", sodiemParameter, makhParameter);
        }
    
        public virtual int updateTien(Nullable<long> sotien, string makh)
        {
            var sotienParameter = sotien.HasValue ?
                new ObjectParameter("sotien", sotien) :
                new ObjectParameter("sotien", typeof(long));
    
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTien", sotienParameter, makhParameter);
        }
    
        public virtual int XoaBan(string sOBAN)
        {
            var sOBANParameter = sOBAN != null ?
                new ObjectParameter("SOBAN", sOBAN) :
                new ObjectParameter("SOBAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaBan", sOBANParameter);
        }
    
        public virtual int xoakhachhang(string makh)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoakhachhang", makhParameter);
        }
    
        public virtual int xoamonan(string mamon)
        {
            var mamonParameter = mamon != null ?
                new ObjectParameter("mamon", mamon) :
                new ObjectParameter("mamon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoamonan", mamonParameter);
        }
    
        public virtual int xoanhanvien(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoanhanvien", manvParameter);
        }
    
        public virtual int XoaThucUong(string mathucuong)
        {
            var mathucuongParameter = mathucuong != null ?
                new ObjectParameter("mathucuong", mathucuong) :
                new ObjectParameter("mathucuong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaThucUong", mathucuongParameter);
        }
    }
}
