//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANHE_HD_DKKM
    {
        public string MAHD { get; set; }
        public string MADIEUKIENKM { get; set; }
        public Nullable<decimal> TONGTIENHD { get; set; }
        public Nullable<decimal> TIENGIAM { get; set; }
    
        public virtual DIEUKIENKM DIEUKIENKM { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
