//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYENHAN
    {
        public string MAQH { get; set; }
        public string TENQH { get; set; }
        public string MOTA { get; set; }
        public string MACV { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
    }
}
