//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCUONG
    {
        public THUCUONG()
        {
            this.CTHD_TU = new HashSet<CTHD_TU>();
            this.TONKHOes = new HashSet<TONKHO>();
        }
    
        public string MATHUCUONG { get; set; }
        public string TENTHUCUONG { get; set; }
        public string MOTA { get; set; }
        public string DVT { get; set; }
        public Nullable<int> GIABAN { get; set; }
        public byte[] HINH { get; set; }
        public string matrangthai { get; set; }
        public Nullable<System.DateTime> NGAYXOATHUCUONG { get; set; }
    
        public virtual ICollection<CTHD_TU> CTHD_TU { get; set; }
        public virtual ICollection<TONKHO> TONKHOes { get; set; }
    }
}
