//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva_vegan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public string MAKHO { get; set; }
        public string MANGUYENLIEU { get; set; }
        public string MATHUCUONG { get; set; }
        public Nullable<double> SOLUONGTON { get; set; }
    
        public virtual KHO KHO { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual THUCUONG THUCUONG { get; set; }
    }
}
